[package]
name = "sysmon-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
sysinfo = "0.30"        # system info: CPU, memory, etc.
ratatui = "0.26"        # terminal UI
crossterm = "0.27"      # terminal input/output
chrono = "0.4"          # time formatting
